//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //
  public Integer onedone;
   public Integer isexpressioncondition;
   /**
    * f0 -> ( ExternalDeclaration() )+
    */
   public R visit(TranslationUnit n) {
      R _ret=null;
       onedone=0;
      isexpressioncondition=0;
      System.out.println("package main");
      System.out.println("import \"fmt\"");
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( FunctionDefinition() | Declaration() )
    */
   public R visit(ExternalDeclaration n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> [ DeclarationSpecifiers() ]
    * f1 -> Declarator()
    * f2 -> [ DeclarationList() ]
    * f3 -> CompoundStatement()
    */
   public R visit(FunctionDefinition n) {
      R _ret=null;
      System.out.print("func ");
      n.f1.accept(this);
      System.out.print("(");
      
      n.f2.accept(this);
      System.out.print(") ");
      n.f0.accept(this);
      
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> [ InitDeclaratorList() ]
    * f2 -> ";"
    */
   public R visit(Declaration n) {
      R _ret=null;
      System.out.print("var ");
      
      n.f1.accept(this);
      System.out.print(" ");
      n.f0.accept(this);
      n.f2.accept(this);
      System.out.println("");
      return _ret;
   }

   /**
    * f0 -> ( Declaration() )+
    */
   public R visit(DeclarationList n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> TypeSpecifier()
    * f1 -> [ DeclarationSpecifiers() ]
    */
   public R visit(DeclarationSpecifiers n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <VOID> | <CHAR> | <INT> | <LONG> | <FLOAT> | <DOUBLE> )
    */
   public R visit(TypeSpecifier n) {
      R _ret=null;
      if(n.f0.which==0)
         System.out.print("");
      else if(n.f0.which==1)
         System.out.print("char");
      else if(n.f0.which==2)
         System.out.print("int");
      else if(n.f0.which==3)
         System.out.print("long");
      else if(n.f0.which==4)
         System.out.print("float");
      else if(n.f0.which==5)
         System.out.print("double");
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> InitDeclarator()
    * f1 -> ( "," InitDeclarator() )*
    */
   public R visit(InitDeclaratorList n) {
      R _ret=null;
      n.f0.accept(this);
      onedone=1;
      n.f1.accept(this);
      onedone=0;
      return _ret;
   }

   /**
    * f0 -> Declarator()
    * f1 -> [ "=" Initializer() ]
    */
   public R visit(InitDeclarator n) {
      R _ret=null;
      if(onedone==1)
         System.out.print(",");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> TypeSpecifier()
    * f1 -> [ SpecifierQualifierList() ]
    */
   public R visit(SpecifierQualifierList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> Enumerator()
    * f1 -> ( "," Enumerator() )*
    */
   public R visit(EnumeratorList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> [ "=" ConstantExpression() ]
    */
   public R visit(Enumerator n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> [ Pointer() ]
    * f1 -> DirectDeclarator()
    */
   public R visit(Declarator n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( t=<IDENTIFIER> | "(" Declarator() ")" )
    * f1 -> ( "[" [ ConstantExpression() ] "]" | "(" ParameterTypeList() ")" | "(" [ IdentifierList() ] ")" )*
    */
   public R visit(DirectDeclarator n) {
      R _ret=null;
      if(n.f0.which==0)
         System.out.print(((n.f0.choice)).toString());
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "*"
    * f1 -> [ Pointer() ]
    */
   public R visit(Pointer n) {
      R _ret=null;
      System.out.print("*");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ParameterList()
    * f1 -> [ "," "..." ]
    */
   public R visit(ParameterTypeList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ParameterDeclaration()
    * f1 -> ( "," ParameterDeclaration() )*
    */
   public R visit(ParameterList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> ( Declarator() | [ AbstractDeclarator() ] )
    */
   public R visit(ParameterDeclaration n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public R visit(IdentifierList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( AssignmentExpression() | Initializer1() )
    */
   public R visit(Initializer n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> InitializerList()
    * f2 -> [ comma() ]
    * f3 -> "}"
    */
   public R visit(Initializer1 n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> ","
    */
   public R visit(comma n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> Initializer()
    * f1 -> ( "," Initializer() )*
    */
   public R visit(InitializerList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> [ AbstractDeclarator() ]
    */
   public R visit(TypeName n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( Pointer() | AbstractDeclarator1() )
    */
   public R visit(AbstractDeclarator n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> [ Pointer() ]
    * f1 -> DirectAbstractDeclarator()
    */
   public R visit(AbstractDeclarator1 n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( "(" AbstractDeclarator() ")" | "[" [ ConstantExpression() ] "]" | "(" [ ParameterTypeList() ] ")" )
    * f1 -> ( "[" [ ConstantExpression() ] "]" | "(" [ ParameterTypeList() ] ")" )*
    */
   public R visit(DirectAbstractDeclarator n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( LabeledStatement() | ExpressionStatement() | CompoundStatement() | SelectionStatement() | IterationStatement() | JumpStatement() )
    */
   public R visit(Statement n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( GotoLabel() | CaseLabel() | DefaultLabel() )
    */
   public R visit(LabeledStatement n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public R visit(GotoLabel n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> <CASE>
    * f1 -> ConstantExpression()
    * f2 -> ":"
    * f3 -> Statement()
    */
   public R visit(CaseLabel n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> <DFLT>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public R visit(DefaultLabel n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> [ Expression() ]
    * f1 -> ";"
    */
   public R visit(ExpressionStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      System.out.println("");
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> [ DeclarationList() ]
    * f2 -> [ StatementList() ]
    * f3 -> "}"
    */
   public R visit(CompoundStatement n) {
      R _ret=null;
      System.out.println("{");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      System.out.println("}");
      return _ret;
   }

   /**
    * f0 -> ( Statement() )+
    */
   public R visit(StatementList n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( IfStatement() | SwitchStatement() )
    */
   public R visit(SelectionStatement n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> [ <ELSE> Statement() ]
    */
   public R visit(IfStatement n) {
      R _ret=null;
      System.out.print("if ");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      System.out.println("{");
      n.f4.accept(this);
      System.out.print("}");
      if(n.f5.present())
      System.out.println("else{");
      n.f5.accept(this);
      if(n.f5.present())
      System.out.println("}");
      else
      System.out.println("");
      return _ret;
   }

   /**
    * f0 -> <SWITCH>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(SwitchStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( WhileStatement() | DoWhileStatement() | ForStatement() )
    */
   public R visit(IterationStatement n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <WHILE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      return _ret;
   }

   /**
    * f0 -> <DO>
    * f1 -> Statement()
    * f2 -> <WHILE>
    * f3 -> "("
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public R visit(DoWhileStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      return _ret;
   }

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> [ Expression() ]
    * f3 -> ";"
    * f4 -> [ Expression() ]
    * f5 -> ";"
    * f6 -> [ Expression() ]
    * f7 -> ")"
    * f8 -> Statement()
    */
   public R visit(ForStatement n) {
      R _ret=null;
      System.out.print("for ");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      System.out.print(";");
      n.f4.accept(this);
      n.f5.accept(this);
      System.out.print(";");
      n.f6.accept(this);
      n.f7.accept(this);
      
      System.out.println("{");
      n.f8.accept(this);
      System.out.println("}");
      
      return _ret;
   }

   /**
    * f0 -> ( <GOTO> <IDENTIFIER> ";" | <CONTINUE> ";" | <BREAK> ";" | <RETURN> [ Expression() ] ";" )
    */
   public R visit(JumpStatement n) {
      R _ret=null;
      if(n.f0.which==3)
         System.out.print("return ");
      n.f0.accept(this);
      System.out.println("");     
      return _ret;
   }

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public R visit(Expression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> UnaryExpression() AssignmentOperator() AssignmentExpression()
    *       | ConditionalExpression()
    */
   public R visit(AssignmentExpression n) {
      R _ret=null;
      if(onedone==1)
         System.out.print(",");
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( "=" | "*=" | "/=" | "%=" | "+=" | "-=" | "<<=" | ">>=" | "&=" | "^=" | "|=" )
    */
   public R visit(AssignmentOperator n) {
      R _ret=null;
      switch(n.f0.which){
         case 0: System.out.print("=");break;
         case 1: System.out.print("*=");break;
         case 2: System.out.print("/=");break;
         case 3: System.out.print("%=");break;
         case 4: System.out.print("+=");break;
         case 5: System.out.print("-=");break;
         case 6: System.out.print("<<=");break;
         case 7: System.out.print(">>=");break;
         case 8: System.out.print("&=");break;
         case 9: System.out.print("^=");break;
         case 10: System.out.print("!=");break;
         default: break;
         
      }
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> LogicalORExpression()
    * f1 -> [ ConditionalSubExpression() ]
    */
   public R visit(ConditionalExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "?"
    * f1 -> Expression()
    * f2 -> ":"
    * f3 -> ConditionalExpression()
    */
   public R visit(ConditionalSubExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> ConditionalExpression()
    */
   public R visit(ConstantExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> LogicalANDExpression()
    * f1 -> [ "||" LogicalORExpression() ]
    */
   public R visit(LogicalORExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> InclusiveORExpression()
    * f1 -> [ "&&" LogicalANDExpression() ]
    */
   public R visit(LogicalANDExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ExclusiveORExpression()
    * f1 -> [ "|" InclusiveORExpression() ]
    */
   public R visit(InclusiveORExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ANDExpression()
    * f1 -> [ "^" ExclusiveORExpression() ]
    */
   public R visit(ExclusiveORExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> EqualityExpression()
    * f1 -> [ "&" ANDExpression() ]
    */
   public R visit(ANDExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> RelationalExpression()
    * f1 -> [ EqualitySymbols() ]
    */
   public R visit(EqualityExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> EqualityExpression1()
    *       | EqualityExpression2()
    */
   public R visit(EqualitySymbols n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "=="
    * f1 -> EqualityExpression()
    */
   public R visit(EqualityExpression1 n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print("==");
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "!="
    * f1 -> EqualityExpression()
    */
   public R visit(EqualityExpression2 n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print("!=");
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ShiftExpression()
    * f1 -> [ RelationalSymbols() ]
    */
   public R visit(RelationalExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> RelationalExpression1()
    *       | RelationalExpression2()
    *       | RelationalExpression3()
    *       | RelationalExpression4()
    */
   public R visit(RelationalSymbols n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<"
    * f1 -> RelationalExpression()
    */
   public R visit(RelationalExpression1 n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print("<");
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ">"
    * f1 -> RelationalExpression()
    */
   public R visit(RelationalExpression2 n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print(">");
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<="
    * f1 -> RelationalExpression()
    */
   public R visit(RelationalExpression3 n) {
      R _ret=null;
      System.out.print("<=");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ">="
    * f1 -> RelationalExpression()
    */
   public R visit(RelationalExpression4 n) {
      R _ret=null;
      System.out.print(">=");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> AdditiveExpression()
    * f1 -> [ ShiftSymbols() ]
    */
   public R visit(ShiftExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ShiftExpression1()
    *       | ShiftExpression2()
    */
   public R visit(ShiftSymbols n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<<"
    * f1 -> ShiftExpression()
    */
   public R visit(ShiftExpression1 n) {
      R _ret=null;
      System.out.print("<<");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ">>"
    * f1 -> ShiftExpression()
    */
   public R visit(ShiftExpression2 n) {
      R _ret=null;
      System.out.print(">>");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> MultiplicativeExpression()
    * f1 -> [ AddSymbols() ]
    */
   public R visit(AdditiveExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> AdditiveExpression1()
    *       | AdditiveExpression2()
    */
   public R visit(AddSymbols n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "+"
    * f1 -> AdditiveExpression()
    */
   public R visit(AdditiveExpression1 n) {
      R _ret=null;
      System.out.print("+");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "-"
    * f1 -> AdditiveExpression()
    */
   public R visit(AdditiveExpression2 n) {
      R _ret=null;
      System.out.print("-");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> CastExpression()
    * f1 -> [ MulSymbols() ]
    */
   public R visit(MultiplicativeExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> MultiplicativeExpression1()
    *       | MultiplicativeExpression2()
    *       | MultiplicativeExpression3()
    */
   public R visit(MulSymbols n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "*"
    * f1 -> MultiplicativeExpression()
    */
   public R visit(MultiplicativeExpression1 n) {
      R _ret=null;
      System.out.print("*");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "/"
    * f1 -> MultiplicativeExpression()
    */
   public R visit(MultiplicativeExpression2 n) {
      R _ret=null;
      System.out.print("/");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "%"
    * f1 -> MultiplicativeExpression()
    */
   public R visit(MultiplicativeExpression3 n) {
      R _ret=null;
      System.out.print("%");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( CastExpression1() | UnaryExpression() )
    */
   public R visit(CastExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> TypeName()
    * f2 -> ")"
    * f3 -> CastExpression()
    */
   public R visit(CastExpression1 n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( UnaryExpression1() | UnaryExpression2() | UnaryExpression3() | UnaryExpression4() )
    */
   public R visit(UnaryExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> PostfixExpression()
    */
   public R visit(UnaryExpression1 n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "++"
    * f1 -> UnaryExpression()
    */
   public R visit(UnaryExpression2 n) {
      R _ret=null;
      System.out.print("++");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "--"
    * f1 -> UnaryExpression()
    */
   public R visit(UnaryExpression3 n) {
      R _ret=null;
      System.out.print("--");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> UnaryOperator()
    * f1 -> CastExpression()
    */
   public R visit(UnaryExpression4 n) {
      R _ret=null;
      
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( "&" | "*" | "+" | "-" | "~" | "!" )
    */
   public R visit(UnaryOperator n) {
      R _ret=null;
      n.f0.accept(this);
      switch(n.f0.which){
         case 0: System.out.print("&");break;
         case 1: System.out.print("*");break;
         case 2: System.out.print("+");break;
         case 3: System.out.print("-");break;
         case 4: System.out.print("~");break;
         case 5: System.out.print("!");break;
         default: break;

      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> ( PostfixExpression1() | "(" [ ArgumentExpressionList() ] ")" | PostfixExpression3() | PostfixExpression4() | PostfixExpression5() | PostfixExpression6() )*
    */
   public R visit(PostfixExpression n) {
      R _ret=null;
      n.f0.accept(this);
      if(n.f1.size()>0){
      if(((NodeChoice)(n.f1.elementAt(0))).which==1)
         System.out.print("(");
      n.f1.accept(this);
      if(((NodeChoice)(n.f1.elementAt(0))).which==1)
         System.out.print(")");
      }
      return _ret;
   }

   /**
    * f0 -> "["
    * f1 -> Expression()
    * f2 -> "]"
    */
   public R visit(PostfixExpression1 n) {
      R _ret=null;
      System.out.print("[");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      System.out.print("]");
      return _ret;
   }

   /**
    * f0 -> "."
    * f1 -> <IDENTIFIER>
    */
   public R visit(PostfixExpression3 n) {
      R _ret=null;
      System.out.print("."+n.f1.toString());
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "->"
    * f1 -> <IDENTIFIER>
    */
   public R visit(PostfixExpression4 n) {
      R _ret=null;
      System.out.print("->"+n.f1.toString());
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "++"
    */
   public R visit(PostfixExpression5 n) {
      R _ret=null;
      System.out.print("++");
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "--"
    */
   public R visit(PostfixExpression6 n) {
      R _ret=null;
      System.out.print("--");
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ( <IDENTIFIER> | Constant() | "(" Expression() ")" )
    */
   public R visit(PrimaryExpression n) {
      R _ret=null;
      if(n.f0.which==0)
         {
            if(n.f0.choice.toString().equals("printf"))
               System.out.print("fmt.Printf");
            else System.out.print(n.f0.choice.toString());
         }  
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public R visit(ArgumentExpressionList n) {
      R _ret=null;
      n.f0.accept(this);
      onedone=1;
      n.f1.accept(this);
      onedone=0;
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <CHARACTER_LITERAL>
    *       | <STRING_LITERAL>
    */
   public R visit(Constant n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print(" "+n.f0.choice.toString()+" ");
           return _ret;
   }

}
