//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "if"
 * f1 -> Expression()
 * f2 -> Statement()
 * f3 -> [ "else" Statement() ]
 */
public class IfStatement implements Node {
   public NodeToken f0;
   public Expression f1;
   public Statement f2;
   public NodeOptional f3;

   public IfStatement(NodeToken n0, Expression n1, Statement n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public IfStatement(Expression n0, Statement n1, NodeOptional n2) {
      f0 = new NodeToken("if");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

