//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ExternalDeclaration() )+
    */
   public void visit(TranslationUnit n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( FunctionDefinition() | Declaration() )
    */
   public void visit(ExternalDeclaration n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> [ DeclarationSpecifiers() ]
    * f1 -> Declarator()
    * f2 -> [ DeclarationList() ]
    * f3 -> CompoundStatement()
    */
   public void visit(FunctionDefinition n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> [ InitDeclaratorList() ]
    * f2 -> ";"
    */
   public void visit(Declaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> ( Declaration() )+
    */
   public void visit(DeclarationList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> TypeSpecifier()
    * f1 -> [ DeclarationSpecifiers() ]
    */
   public void visit(DeclarationSpecifiers n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( <VOID> | <CHAR> | <INT> | <LONG> | <FLOAT> | <DOUBLE> )
    */
   public void visit(TypeSpecifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> InitDeclarator()
    * f1 -> ( "," InitDeclarator() )*
    */
   public void visit(InitDeclaratorList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Declarator()
    * f1 -> [ "=" Initializer() ]
    */
   public void visit(InitDeclarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> TypeSpecifier()
    * f1 -> [ SpecifierQualifierList() ]
    */
   public void visit(SpecifierQualifierList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Enumerator()
    * f1 -> ( "," Enumerator() )*
    */
   public void visit(EnumeratorList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> [ "=" ConstantExpression() ]
    */
   public void visit(Enumerator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> [ Pointer() ]
    * f1 -> DirectDeclarator()
    */
   public void visit(Declarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( t=<IDENTIFIER> | "(" Declarator() ")" )
    * f1 -> ( "[" [ ConstantExpression() ] "]" | "(" ParameterTypeList() ")" | "(" [ IdentifierList() ] ")" )*
    */
   public void visit(DirectDeclarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "*"
    * f1 -> [ Pointer() ]
    */
   public void visit(Pointer n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ParameterList()
    * f1 -> [ "," "..." ]
    */
   public void visit(ParameterTypeList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ParameterDeclaration()
    * f1 -> ( "," ParameterDeclaration() )*
    */
   public void visit(ParameterList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> ( Declarator() | [ AbstractDeclarator() ] )
    */
   public void visit(ParameterDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public void visit(IdentifierList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( AssignmentExpression() | Initializer1() )
    */
   public void visit(Initializer n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "{"
    * f1 -> InitializerList()
    * f2 -> [ comma() ]
    * f3 -> "}"
    */
   public void visit(Initializer1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> ","
    */
   public void visit(comma n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Initializer()
    * f1 -> ( "," Initializer() )*
    */
   public void visit(InitializerList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> [ AbstractDeclarator() ]
    */
   public void visit(TypeName n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( Pointer() | AbstractDeclarator1() )
    */
   public void visit(AbstractDeclarator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> [ Pointer() ]
    * f1 -> DirectAbstractDeclarator()
    */
   public void visit(AbstractDeclarator1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( "(" AbstractDeclarator() ")" | "[" [ ConstantExpression() ] "]" | "(" [ ParameterTypeList() ] ")" )
    * f1 -> ( "[" [ ConstantExpression() ] "]" | "(" [ ParameterTypeList() ] ")" )*
    */
   public void visit(DirectAbstractDeclarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( LabeledStatement() | ExpressionStatement() | CompoundStatement() | SelectionStatement() | IterationStatement() | JumpStatement() )
    */
   public void visit(Statement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( GotoLabel() | CaseLabel() | DefaultLabel() )
    */
   public void visit(LabeledStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public void visit(GotoLabel n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <CASE>
    * f1 -> ConstantExpression()
    * f2 -> ":"
    * f3 -> Statement()
    */
   public void visit(CaseLabel n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <DFLT>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public void visit(DefaultLabel n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> [ Expression() ]
    * f1 -> ";"
    */
   public void visit(ExpressionStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "{"
    * f1 -> [ DeclarationList() ]
    * f2 -> [ StatementList() ]
    * f3 -> "}"
    */
   public void visit(CompoundStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> ( Statement() )+
    */
   public void visit(StatementList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( IfStatement() | SwitchStatement() )
    */
   public void visit(SelectionStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> [ <ELSE> Statement() ]
    */
   public void visit(IfStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> <SWITCH>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(SwitchStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> ( WhileStatement() | DoWhileStatement() | ForStatement() )
    */
   public void visit(IterationStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <WHILE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(WhileStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <DO>
    * f1 -> Statement()
    * f2 -> <WHILE>
    * f3 -> "("
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public void visit(DoWhileStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> [ Expression() ]
    * f3 -> ";"
    * f4 -> [ Expression() ]
    * f5 -> ";"
    * f6 -> [ Expression() ]
    * f7 -> ")"
    * f8 -> Statement()
    */
   public void visit(ForStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> ( <GOTO> <IDENTIFIER> ";" | <CONTINUE> ";" | <BREAK> ";" | <RETURN> [ Expression() ] ";" )
    */
   public void visit(JumpStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public void visit(Expression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> UnaryExpression() AssignmentOperator() AssignmentExpression()
    *       | ConditionalExpression()
    */
   public void visit(AssignmentExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( "=" | "*=" | "/=" | "%=" | "+=" | "-=" | "<<=" | ">>=" | "&=" | "^=" | "|=" )
    */
   public void visit(AssignmentOperator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> LogicalORExpression()
    * f1 -> [ ConditionalSubExpression() ]
    */
   public void visit(ConditionalExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "?"
    * f1 -> Expression()
    * f2 -> ":"
    * f3 -> ConditionalExpression()
    */
   public void visit(ConditionalSubExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> ConditionalExpression()
    */
   public void visit(ConstantExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> LogicalANDExpression()
    * f1 -> [ "||" LogicalORExpression() ]
    */
   public void visit(LogicalORExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> InclusiveORExpression()
    * f1 -> [ "&&" LogicalANDExpression() ]
    */
   public void visit(LogicalANDExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ExclusiveORExpression()
    * f1 -> [ "|" InclusiveORExpression() ]
    */
   public void visit(InclusiveORExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ANDExpression()
    * f1 -> [ "^" ExclusiveORExpression() ]
    */
   public void visit(ExclusiveORExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> EqualityExpression()
    * f1 -> [ "&" ANDExpression() ]
    */
   public void visit(ANDExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> RelationalExpression()
    * f1 -> [ EqualitySymbols() ]
    */
   public void visit(EqualityExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> EqualityExpression1()
    *       | EqualityExpression2()
    */
   public void visit(EqualitySymbols n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "=="
    * f1 -> EqualityExpression()
    */
   public void visit(EqualityExpression1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "!="
    * f1 -> EqualityExpression()
    */
   public void visit(EqualityExpression2 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ShiftExpression()
    * f1 -> [ RelationalSymbols() ]
    */
   public void visit(RelationalExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> RelationalExpression1()
    *       | RelationalExpression2()
    *       | RelationalExpression3()
    *       | RelationalExpression4()
    */
   public void visit(RelationalSymbols n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "<"
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalExpression1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ">"
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalExpression2 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "<="
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalExpression3 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ">="
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalExpression4 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AdditiveExpression()
    * f1 -> [ ShiftSymbols() ]
    */
   public void visit(ShiftExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ShiftExpression1()
    *       | ShiftExpression2()
    */
   public void visit(ShiftSymbols n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "<<"
    * f1 -> ShiftExpression()
    */
   public void visit(ShiftExpression1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ">>"
    * f1 -> ShiftExpression()
    */
   public void visit(ShiftExpression2 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> MultiplicativeExpression()
    * f1 -> [ AddSymbols() ]
    */
   public void visit(AdditiveExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AdditiveExpression1()
    *       | AdditiveExpression2()
    */
   public void visit(AddSymbols n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "+"
    * f1 -> AdditiveExpression()
    */
   public void visit(AdditiveExpression1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "-"
    * f1 -> AdditiveExpression()
    */
   public void visit(AdditiveExpression2 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> CastExpression()
    * f1 -> [ MulSymbols() ]
    */
   public void visit(MultiplicativeExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> MultiplicativeExpression1()
    *       | MultiplicativeExpression2()
    *       | MultiplicativeExpression3()
    */
   public void visit(MulSymbols n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "*"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeExpression1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "/"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeExpression2 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "%"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeExpression3 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( CastExpression1() | UnaryExpression() )
    */
   public void visit(CastExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> TypeName()
    * f2 -> ")"
    * f3 -> CastExpression()
    */
   public void visit(CastExpression1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> ( UnaryExpression1() | UnaryExpression2() | UnaryExpression3() | UnaryExpression4() )
    */
   public void visit(UnaryExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> PostfixExpression()
    */
   public void visit(UnaryExpression1 n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "++"
    * f1 -> UnaryExpression()
    */
   public void visit(UnaryExpression2 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "--"
    * f1 -> UnaryExpression()
    */
   public void visit(UnaryExpression3 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> UnaryOperator()
    * f1 -> CastExpression()
    */
   public void visit(UnaryExpression4 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( "&" | "*" | "+" | "-" | "~" | "!" )
    */
   public void visit(UnaryOperator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> ( PostfixExpression1() | "(" [ ArgumentExpressionList() ] ")" | PostfixExpression3() | PostfixExpression4() | PostfixExpression5() | PostfixExpression6() )*
    */
   public void visit(PostfixExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "["
    * f1 -> Expression()
    * f2 -> "]"
    */
   public void visit(PostfixExpression1 n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "."
    * f1 -> <IDENTIFIER>
    */
   public void visit(PostfixExpression3 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "->"
    * f1 -> <IDENTIFIER>
    */
   public void visit(PostfixExpression4 n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "++"
    */
   public void visit(PostfixExpression5 n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "--"
    */
   public void visit(PostfixExpression6 n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <IDENTIFIER> | Constant() | "(" Expression() ")" )
    */
   public void visit(PrimaryExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public void visit(ArgumentExpressionList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <CHARACTER_LITERAL>
    *       | <STRING_LITERAL>
    */
   public void visit(Constant n) {
      n.f0.accept(this);
   }

}
