//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   int inFor = 0;
   public R visit(NodeList n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //

  
   /**
    * f0 -> Packages()
    * f1 -> Imports()
    * f2 -> ( FunctionDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n) {
      R _ret=null;
      System.out.println("#include<stdio.h>");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> PackageOther()
    *       | PackageMain()
    */
   public R visit(Packages n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "package"
    * f1 -> Identifier()
    */
   public R visit(PackageOther n) {
      R _ret=null;
      n.f0.accept(this);
//       n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "package"
    * f1 -> "main"
    */
   public R visit(PackageMain n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> SingleImport()
    *       | MultipleImport()
    */
   public R visit(Imports n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "\""
    * f2 -> Identifier()
    * f3 -> "\""
    */
   public R visit(SingleImport n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
//       n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "("
    * f2 -> ( "\"" Identifier() "\"" )*
    * f3 -> ")"
    */
   public R visit(MultipleImport n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
//       n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> MainFunctionDeclaration()
    *       | OtherFunctionDeclaration()
    */
   public R visit(FunctionDeclaration n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "func"
    * f1 -> "main"
    * f2 -> "("
    * f3 -> ")"
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( Statement() )*
    * f7 -> "}"
    */
   public R visit(MainFunctionDeclaration n) {
      R _ret=null;
      System.out.println("main() {");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      System.out.println("}");
      return _ret;
   }

   /**
    * f0 -> "func"
    * f1 -> Identifier()
    * f2 -> Signature()
    * f3 -> [ Type() ]
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( Statement() )*
    * f7 -> [ ReturnExpression() ]
    * f8 -> "}"
    */
   public R visit(OtherFunctionDeclaration n) {
      R _ret=null;
      System.out.print("int ");
      n.f0.accept(this);
      n.f1.accept(this);
      System.out.print("(");
      n.f2.accept(this);
      System.out.print(")");
      n.f3.accept(this);
      System.out.println("{");
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      System.out.println("}");
      return _ret;
   }

   /**
    * f0 -> "return"
    * f1 -> Expression()
    */
   public R visit(ReturnExpression n) {
      R _ret=null;
      System.out.print("return ");
      n.f0.accept(this);
      n.f1.accept(this);
      System.out.println(";");
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> [ VarType() ( CommaVarType() )* ]
    * f2 -> ")"
    */
   public R visit(Signature n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> Type()
    */
   public R visit(VarType n) {
      R _ret=null;
      System.out.print("int ");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> VarType()
    */
   public R visit(CommaVarType n) {
      R _ret=null;
      System.out.print(",");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(Type n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print(n.f0.toString());
      return _ret;
   }

   /**
    * f0 -> PrintStatement()
    *       | Block()
    *       | IfStatement()
    *       | WhileStatement()
    *       | ForStatement()
    *       | AssignmentStatement()
    *       | Expression()
    */
   public R visit(Statement n) {
      R _ret=null;
      int temp = inFor;
      if(inFor == 1){
			inFor = 0;
		}
	  
      n.f0.accept(this);
      inFor = temp;
      if((n.f0.which == 0 || n.f0.which == 5 || n.f0.which == 6) && inFor==0)
			System.out.println(";");
	  return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( VarDeclaration() )*
    * f2 -> ( Statement() )*
    * f3 -> "}"
    */
   public R visit(Block n) {
      R _ret=null;
      System.out.println("{");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      System.out.println("}");
      return _ret;
   }

   /**
    * f0 -> "var"
    * f1 -> Identifier()
    * f2 -> ( CommaIdentifier() )*
    * f3 -> Type()
    */
   public R visit(VarDeclaration n) {
      R _ret=null;
      System.out.print("int ");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      System.out.println(";");
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Identifier()
    */
   public R visit(CommaIdentifier n) {
      R _ret=null;
      System.out.print(", ");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> AssignmentOperator()
    * f2 -> Expression()
    */
   public R visit(AssignmentStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> "="
    *       | "*="
    *       | "/="
    *       | "%="
    *       | "+="
    *       | "-="
    *       | "<<="
    *       | ">>="
    *       | "&="
    *       | "^="
    *       | "|="
    */
   public R visit(AssignmentOperator n) {
      R _ret=null;
      n.f0.accept(this);
      switch(n.f0.which) {
      case 0: System.out.print("=");break;
      case 1: System.out.print("*=");break;
      case 2: System.out.print("/=");break;
      case 3: System.out.print("%=");break;
      case 4: System.out.print("+=");break;
      case 5: System.out.print("-=");break;
      case 6: System.out.print("<<=");break;
      case 7: System.out.print(">>=");break;
      case 8: System.out.print("^=");break;
      case 9: System.out.print("|=");break;
      }
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> Expression()
    * f2 -> Statement()
    * f3 -> [ ElseStatement() ]
    */
   public R visit(IfStatement n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print("if (");
      n.f1.accept(this);
      System.out.println(")");
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> "else"
    * f1 -> Statement()
    */
   public R visit(ElseStatement n) {
      R _ret=null;
      System.out.print(" else ");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> Expression()
    * f2 -> Statement()
    */
   public R visit(WhileStatement n) {
      R _ret=null;
      System.out.print(" while (");
      n.f0.accept(this);
      n.f1.accept(this);
      System.out.println(")");
      n.f2.accept(this);
      return _ret;
   }
   /**
    * f0 -> "for"
    * f1 -> [ AssignmentStatement() ]
    * f2 -> ";"
    * f3 -> [ Expression() ]
    * f4 -> ";"
    * f5 -> [ Statement() ]
    * f6 -> Statement()
    */
   public R visit(ForStatement n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print("for (");
      n.f1.accept(this);
      n.f2.accept(this);
      System.out.print(";");
      n.f3.accept(this);
      n.f4.accept(this);
      System.out.print(";");
      inFor  = 1;
      n.f5.accept(this);
      inFor = 0;
      System.out.println(")");
      n.f6.accept(this);
      return _ret;
   }

   /**
    * f0 -> PrintlnStatement()
    *       | PrintfStatement()
    */
   public R visit(PrintStatement n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "fmt.Println"
    * f1 -> StringPrint()
    */
   public R visit(PrintlnStatement n) {
      R _ret=null;
      System.out.print("printf(");
      n.f0.accept(this);
      n.f1.accept(this);
      System.out.println("printf(\"\\n\");");
      return _ret;
   }

   /**
    * f0 -> "fmt.Printf"
    * f1 -> StringPrint()
    */
   public R visit(PrintfStatement n) {
      R _ret=null;
      System.out.print("printf");
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> StringMsg()
    * f2 -> ( CommaExpression() )*
    * f3 -> ")"
    */
   public R visit(StringPrint n) {
      R _ret=null;
      System.out.print("(");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      System.out.print(")");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> [ Operator() Expression() ]
    */
   public R visit(Expression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "+"
    *       | "-"
    *       | "*"
    *       | "/"
    *       | "%"
    *       | "<"
    *       | ">"
    *       | "=="
    *       | ">="
    *       | "<="
    *       | "!="
    *       | ">>"
    *       | "<<"
    *       | "&"
    *       | "&&"
    *       | "|"
    *       | "||"
    *       | "^"
    *       | "^="
    *       | "&="
    *       | "|="
    */
   public R visit(Operator n) {
      R _ret=null;
      n.f0.accept(this);
      switch(n.f0.which) {
      case 0:System.out.print("+");break;
      case 1:System.out.print("-");break;
      case 2:System.out.print("*");break;
      case 3:System.out.print("/");break;
      case 4:System.out.print("%");break;
      case 5:System.out.print("<");break;
      case 6:System.out.print(">");break;
      case 7:System.out.print("==");break;
      case 8:System.out.print(">=");break;
      case 9:System.out.print("<=");break;
      case 10:System.out.print("!=");break;
      case 11:System.out.print(">>");break;
      case 12:System.out.print("<<");break;
      case 13:System.out.print("&");break;
      case 14:System.out.print("&&");break;
      case 15:System.out.print("|");break;
      case 16:System.out.print("||");break;
      case 17:System.out.print("^");break;
      case 18:System.out.print("^=");break;
      case 19:System.out.print("&=");break;
      case 20:System.out.print("|=");break;
      }
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | Identifier() PostfixExpression()
    *       | BracketExpression() ")"
    *       | StringMsg()
    *       | Identifier()
    */
   public R visit(PrimaryExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> ArrayAccessExpression()
    *       | FunctionArgumentExpression()
    *       | Increment()
    *       | Decrement()
    */
   public R visit(PostfixExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "++"
    */
   public R visit(Increment n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print("++");
      return _ret;
   }

   /**
    * f0 -> "--"
    */
   public R visit(Decrement n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print("--");
      return _ret;
   }

   /**
    * f0 -> ( SingleArrayAccessExpression() )+
    */
   public R visit(ArrayAccessExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "["
    * f1 -> Expression()
    * f2 -> "]"
    */
   public R visit(SingleArrayAccessExpression n) {
      R _ret=null;
      System.out.print("[");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      System.out.print("]");
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> [ ArgumentExpressionList() ]
    * f2 -> ")"
    */
   public R visit(FunctionArgumentExpression n) {
      R _ret=null;
      System.out.print("(");
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      System.out.print(")");
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( CommaExpression() )*
    */
   public R visit(ArgumentExpressionList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(CommaExpression n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print(", ");
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    */
   public R visit(BracketExpression n) {
      R _ret=null;
      System.out.print("(");
      n.f0.accept(this);
      n.f1.accept(this);
      System.out.print(")");
      return _ret;
   }

   /**
    * f0 -> "\""
    * f1 -> ( SubStrinMsg() )*
    * f2 -> "\""
    */
   public R visit(StringMsg n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print("\"");
      n.f1.accept(this);
      n.f2.accept(this);
      System.out.print("\"");
      return _ret;
   }

   /**
    * f0 -> Identifier()
    *       | "."
    *       | Operator()
    *       | ","
    *       | "\\"
    */
   public R visit(SubStrinMsg n) {
      R _ret=null;
      n.f0.accept(this);
      if(n.f0.which == 1 || n.f0.which == 3 || n.f0.which == 4)
		System.out.print(n.f0.choice.toString());
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n) {
      R _ret=null;
      n.f0.accept(this);
      System.out.print(n.f0.toString());
      return _ret;
   }

}
